### ISSUE TITLE
A small mistake in code

### ISSUE THREAD

**Issue by dreamstar0831** [aasensio/deepvel#1]
Dear DeepVel-Team,
        Thanks for sharing your fantastic work.
        I think maybe I find a small mistake in your code:  line 145 in train_deepvel.py (x = self.residual(conv))
        According to the description in your paper about DeepVel, I think this step should be ReLU instead of Residual.
        It's just what puzzles me, maybe I am wrong.

Best regards
Quan

**Comment by aasensio** [comment]
Note that the Keras Convolution2D layer in line 143 also contains the ReLU activation function. Therefore, line 145 implements the first residual layer of Fig. 1 in the paper.
